name: Telegram Music Bot

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install FFmpeg
      run: |
        sudo apt update
        sudo apt install -y ffmpeg

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Start the bot
      run: |
        python3 -m AnonXMusic
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        LOGGER_ID: ${{ secrets.LOGGER_ID }}
        MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}  # Ensure this is set
        STRING_SESSION: ${{ secrets.STRING_SESSION }}
        OWNER_ID: ${{ secrets.OWNER_ID }}
