name: Telegram Music Bot

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can also use 'ubuntu-20.04'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Make sure requirements.txt is in your repo

    - name: Start the bot
      run: |
        python3 -m AnonXMusic  # Make sure the bot starts correctly with this command
        
